name: AntiSystem
main: AntiSystem\Main
version: 1.0.0
api: [2.0.0]
load: POSTWORLD
author: FishingTeam
commands:
 sban:
  description: "Speed Ban"
  permission: "ca.command"
 unsban:
  description: "Unlock Speed Ban"
  permission: "cb.command"
 permissions:
  ca.command:
   default: op
  cb.command:
   default: op  
